### ISSUE TITLE
`msg.flowNodeInstanceId` deprecaten

### ISSUE THREAD

**Issue by matthiasdanne** [5minds/node-red-contrib-processcube#40]
Der `externaltask-input` node gibt `msg.task` und `msg.flowNodeInstanceId` zurück. die flowNodeInstanceId befindet sich aber ebenfalls schon unter `msg.task.flowNodeInstanceId` .

Bei tests ist mir ebenfalls aufgefallen, dass die `externaltask-output` node `msg.task` als input benötigt, `externaltask-error` aber scheinbar `msg.flowNodeInstanceId`.

Was spricht dagegen, `msg.task` als einziges Objekt zu benutzen, mit dem alle ProcessCube nodes arbeiten?

**Comment by moellenbeck** [comment]
@matthiasdanne ich habe mir `...input`, `...output` und `...error` angesehen und, wenn ich nichts übersehen habe, dann wird für die Steuerung `msg.flowNodeInstanceId` verwendet. Ja, es gibt auch `msg.task` und dort ist die `flowNodeInstanceId` auch drin. Die Idee dabei, ist, dass `msg.flowNodeInstanceId` zur Steuerung verwendet wird und `msg.task` als Kontext für den **Nutzer** dient.

@roblen45  was sagst Du zu der Idee?
