### ISSUE TITLE
External Task Worker bleiben stehen bei Parallel Multi Instance

### ISSUE THREAD

**Issue by MarcRaeder01** [5minds/node-red-contrib-processcube#43]
Folgende Situation ist gegeben:

1. Ich Übergebe einer Call Activity (Parallel Multi Instance) ein Array. 
Array = [
  {
    "uid": 14200
  },
  {
    "uid": 14201
  },
  {
    "uid": 14202
  },
  {
    "uid": 14203
  },
  {
    "uid": 14204
  },
  {
    "uid": 14205
  }
]

2. Die Call Activity startet mit dem Array als Start Token (6 Instanzen werden erstellt)
3. Die erste Flow Node ist ein ETW, der in Node Red implementiert ist.
4. Alle Instanzen bis auf eine bleiben bei dem ETW stehen und warten bis sie gepicked werden.
5. Die eine die nicht wartet hat den ETW erfolgreich abgeschlossen und lief weiter
6. Wenn ich im Node Red Flow von dem ETW eine kleine Sache(egal was) verändere und neu auf Deployen drücke, läuft der ETW von einer der wartenden Instanzen weiter.

**Comment by moellenbeck** [comment]
@luisthieme @MarcRaeder01 ich habe mal einen Test aufgenommen:

https://github.com/5minds/node-red-contrib-processcube/tree/develop/processes

Testen:

docker compose build
docker compose up

Studio
Engine: http://localhost:8000

Starten des Prozesses: Call-Activity-Sample

Es werden 2 Instanzen gestartet und beide werden beenden.

**Comment by luisthieme** [comment]
wir hatten heute auch Probleme mit dem Reproduzieren. Bei mir hat auch alles mit multi Instance funktioniert.

**Comment by MarcRaeder01** [comment]
Das Problem hat sich bei uns gelöst. Zum einen hatten wir einen Fehler im Flow (Mehrere Instanzen haben gleichzeitig versucht Emails abzurufen, wurde gelöst durch Semaphore) und wir hatten im Prozess für die Multi Instance eine Call Activity benutzt. Hab mit @S3bastianGriesa gesprochen und konnten das Problem lösen indem wir eine Send Task für die Parallele Multi Instance benutzen. Das Problem lag also nicht bei euch und das Issue hat sich erledigt. Sry für die späte Rückmeldung. Habe es jetzt erst gesehen :(
