### ISSUE TITLE
"Worker error extendLock ... The user aborted a request."

### ISSUE THREAD

**Issue by matthiasdanne** [5minds/node-red-contrib-processcube#50]
Bei ichbindeinauto.de bekommen wir untenstehende Fehlermeldung. Da wir einige ETW umgesetzt haben, haben die Fehlermeldungen mittlerweile eine Quantität erreicht, die die NodeRed-Instanz soweit verlangsamen, dass es negative Auswirkungen auf die Ausführung von Flows hat. (Verzögerte API-Calls, etc.)
Außerdem können wir nicht mehr debuggen, da die Konsole durch die vielen Nachrichten nicht mehr benutzbar ist.

Der Fehler scheint aus der `externaltask-input` node zu kommen. Es ist möglich, die node zu löschen und neuzusetzen, was den Fehler kurzfristig löst, allerdings ist das nicht praktikabel.

Es scheint so zu sein, dass immer, wenn eine ProzessInstanz abgebrochen oder anderweitig nicht mehr gefunden wird, ein Log dazukommt, und sich diese Logs akkumulieren.

```
Worker error extendLock for
*external task flowNodeInstanceId*
*f9ce1163-3602-4099- 8d6e-
f17461dbb254' and *processInstanceId*
*493aea72-f763-4ea2-b6ab-
fd7443ac3a95': The user aborted a
request."
```

https://github.com/user-attachments/assets/ef88b29a-953f-4d49-9ce3-104b4b827e25

**Comment by moellenbeck** [comment]
@matthiasdanne welche Version verwendet ihr? Kannst Du einmal bitte in  "Pakette verwalten" schauen?

**Comment by matthiasdanne** [comment]
Vom node-red-contrib-processcube Paket ist es 1.1.3

![Bildschirmfoto 2024-09-24 um 10 33 16](https://github.com/user-attachments/assets/137bca2c-a35b-4c37-86f1-2e69954c61f3)
